// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewListProductParams creates a new ListProductParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListProductParams() *ListProductParams {
	return &ListProductParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListProductParamsWithTimeout creates a new ListProductParams object
// with the ability to set a timeout on a request.
func NewListProductParamsWithTimeout(timeout time.Duration) *ListProductParams {
	return &ListProductParams{
		timeout: timeout,
	}
}

// NewListProductParamsWithContext creates a new ListProductParams object
// with the ability to set a context for a request.
func NewListProductParamsWithContext(ctx context.Context) *ListProductParams {
	return &ListProductParams{
		Context: ctx,
	}
}

// NewListProductParamsWithHTTPClient creates a new ListProductParams object
// with the ability to set a custom HTTPClient for a request.
func NewListProductParamsWithHTTPClient(client *http.Client) *ListProductParams {
	return &ListProductParams{
		HTTPClient: client,
	}
}

/* ListProductParams contains all the parameters to send to the API endpoint
   for the list product operation.

   Typically these are written to a http.Request.
*/
type ListProductParams struct {

	/* ID.

	   The id of the product for which the operation relates

	   Format: int64
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list product params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListProductParams) WithDefaults() *ListProductParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list product params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListProductParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list product params
func (o *ListProductParams) WithTimeout(timeout time.Duration) *ListProductParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list product params
func (o *ListProductParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list product params
func (o *ListProductParams) WithContext(ctx context.Context) *ListProductParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list product params
func (o *ListProductParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list product params
func (o *ListProductParams) WithHTTPClient(client *http.Client) *ListProductParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list product params
func (o *ListProductParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the list product params
func (o *ListProductParams) WithID(id int64) *ListProductParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the list product params
func (o *ListProductParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ListProductParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
