// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/gr8abbasi/go-microservice/sdk/models"
)

// ListProductReader is a Reader for the ListProduct structure.
type ListProductReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListProductReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListProductOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewListProductNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListProductOK creates a ListProductOK with default headers values
func NewListProductOK() *ListProductOK {
	return &ListProductOK{}
}

/* ListProductOK describes a response with status code 200, with default header values.

A list of products
*/
type ListProductOK struct {
	Payload []*models.Product
}

func (o *ListProductOK) Error() string {
	return fmt.Sprintf("[GET /products/{id}][%d] listProductOK  %+v", 200, o.Payload)
}
func (o *ListProductOK) GetPayload() []*models.Product {
	return o.Payload
}

func (o *ListProductOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListProductNotFound creates a ListProductNotFound with default headers values
func NewListProductNotFound() *ListProductNotFound {
	return &ListProductNotFound{}
}

/* ListProductNotFound describes a response with status code 404, with default header values.

Generic error message returned as a string
*/
type ListProductNotFound struct {
	Payload *models.GenericError
}

func (o *ListProductNotFound) Error() string {
	return fmt.Sprintf("[GET /products/{id}][%d] listProductNotFound  %+v", 404, o.Payload)
}
func (o *ListProductNotFound) GetPayload() *models.GenericError {
	return o.Payload
}

func (o *ListProductNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
